name: quantum-magnetic-field
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - pytest
  - flake8
  - flask
  - colorama
  - pip
  - pip:
    - pytest-cov
